"""teste

Revision ID: 50181023d69c
Revises: 
Create Date: 2024-05-08 19:42:08.731049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50181023d69c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_index('IPK_Artist')

    op.drop_table('Artist')
    op.drop_table('foo')
    with op.batch_alter_table('Track', schema=None) as batch_op:
        batch_op.drop_index('IFK_TrackAlbumId')
        batch_op.drop_index('IFK_TrackGenreId')
        batch_op.drop_index('IFK_TrackMediaTypeId')
        batch_op.drop_index('IPK_Track')

    op.drop_table('Track')
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.drop_index('IFK_CustomerSupportRepId')
        batch_op.drop_index('IPK_Customer')

    op.drop_table('Customer')
    with op.batch_alter_table('Playlist', schema=None) as batch_op:
        batch_op.drop_index('IPK_Playlist')

    op.drop_table('Playlist')
    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.drop_index('IFK_EmployeeReportsTo')
        batch_op.drop_index('IPK_Employee')

    op.drop_table('Employee')
    with op.batch_alter_table('MediaType', schema=None) as batch_op:
        batch_op.drop_index('IPK_MediaType')

    op.drop_table('MediaType')
    with op.batch_alter_table('Invoice', schema=None) as batch_op:
        batch_op.drop_index('IFK_InvoiceCustomerId')
        batch_op.drop_index('IPK_Invoice')

    op.drop_table('Invoice')
    with op.batch_alter_table('Album', schema=None) as batch_op:
        batch_op.drop_index('IFK_AlbumArtistId')
        batch_op.drop_index('IPK_Album')

    op.drop_table('Album')
    with op.batch_alter_table('Genre', schema=None) as batch_op:
        batch_op.drop_index('IPK_Genre')

    op.drop_table('Genre')
    with op.batch_alter_table('PlaylistTrack', schema=None) as batch_op:
        batch_op.drop_index('IFK_PlaylistTrackTrackId')
        batch_op.drop_index('IPK_PlaylistTrack')

    op.drop_table('PlaylistTrack')
    with op.batch_alter_table('InvoiceLine', schema=None) as batch_op:
        batch_op.drop_index('IFK_InvoiceLineInvoiceId')
        batch_op.drop_index('IFK_InvoiceLineTrackId')
        batch_op.drop_index('IPK_InvoiceLine')

    op.drop_table('InvoiceLine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InvoiceLine',
    sa.Column('InvoiceLineId', sa.INTEGER(), nullable=False),
    sa.Column('InvoiceId', sa.INTEGER(), nullable=False),
    sa.Column('TrackId', sa.INTEGER(), nullable=False),
    sa.Column('UnitPrice', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('Quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['InvoiceId'], ['Invoice.InvoiceId'], ),
    sa.ForeignKeyConstraint(['TrackId'], ['Track.TrackId'], ),
    sa.PrimaryKeyConstraint('InvoiceLineId')
    )
    with op.batch_alter_table('InvoiceLine', schema=None) as batch_op:
        batch_op.create_index('IPK_InvoiceLine', ['InvoiceLineId'], unique=1)
        batch_op.create_index('IFK_InvoiceLineTrackId', ['TrackId'], unique=False)
        batch_op.create_index('IFK_InvoiceLineInvoiceId', ['InvoiceId'], unique=False)

    op.create_table('PlaylistTrack',
    sa.Column('PlaylistId', sa.INTEGER(), nullable=False),
    sa.Column('TrackId', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['PlaylistId'], ['Playlist.PlaylistId'], ),
    sa.ForeignKeyConstraint(['TrackId'], ['Track.TrackId'], ),
    sa.PrimaryKeyConstraint('PlaylistId', 'TrackId')
    )
    with op.batch_alter_table('PlaylistTrack', schema=None) as batch_op:
        batch_op.create_index('IPK_PlaylistTrack', ['PlaylistId', 'TrackId'], unique=1)
        batch_op.create_index('IFK_PlaylistTrackTrackId', ['TrackId'], unique=False)

    op.create_table('Genre',
    sa.Column('GenreId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('GenreId')
    )
    with op.batch_alter_table('Genre', schema=None) as batch_op:
        batch_op.create_index('IPK_Genre', ['GenreId'], unique=1)

    op.create_table('Album',
    sa.Column('AlbumId', sa.INTEGER(), nullable=False),
    sa.Column('Title', sa.NVARCHAR(length=160), nullable=False),
    sa.Column('ArtistId', sa.INTEGER(), nullable=False),
    sa.Column('Column1', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['ArtistId'], ['Artist.ArtistId'], ),
    sa.PrimaryKeyConstraint('AlbumId')
    )
    with op.batch_alter_table('Album', schema=None) as batch_op:
        batch_op.create_index('IPK_Album', ['AlbumId'], unique=1)
        batch_op.create_index('IFK_AlbumArtistId', ['ArtistId'], unique=False)

    op.create_table('Invoice',
    sa.Column('InvoiceId', sa.INTEGER(), nullable=False),
    sa.Column('CustomerId', sa.INTEGER(), nullable=False),
    sa.Column('InvoiceDate', sa.DATETIME(), nullable=False),
    sa.Column('BillingAddress', sa.NVARCHAR(length=70), nullable=True),
    sa.Column('BillingCity', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('BillingState', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('BillingCountry', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('BillingPostalCode', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('Total', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['CustomerId'], ['Customer.CustomerId'], ),
    sa.PrimaryKeyConstraint('InvoiceId')
    )
    with op.batch_alter_table('Invoice', schema=None) as batch_op:
        batch_op.create_index('IPK_Invoice', ['InvoiceId'], unique=1)
        batch_op.create_index('IFK_InvoiceCustomerId', ['CustomerId'], unique=False)

    op.create_table('MediaType',
    sa.Column('MediaTypeId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('MediaTypeId')
    )
    with op.batch_alter_table('MediaType', schema=None) as batch_op:
        batch_op.create_index('IPK_MediaType', ['MediaTypeId'], unique=1)

    op.create_table('Employee',
    sa.Column('EmployeeId', sa.INTEGER(), nullable=False),
    sa.Column('LastName', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('FirstName', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Title', sa.NVARCHAR(length=30), nullable=True),
    sa.Column('ReportsTo', sa.INTEGER(), nullable=True),
    sa.Column('BirthDate', sa.DATETIME(), nullable=True),
    sa.Column('HireDate', sa.DATETIME(), nullable=True),
    sa.Column('Address', sa.NVARCHAR(length=70), nullable=True),
    sa.Column('City', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('State', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('Country', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('PostalCode', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('Phone', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Fax', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Email', sa.NVARCHAR(length=60), nullable=True),
    sa.ForeignKeyConstraint(['ReportsTo'], ['Employee.EmployeeId'], ),
    sa.PrimaryKeyConstraint('EmployeeId')
    )
    with op.batch_alter_table('Employee', schema=None) as batch_op:
        batch_op.create_index('IPK_Employee', ['EmployeeId'], unique=1)
        batch_op.create_index('IFK_EmployeeReportsTo', ['ReportsTo'], unique=False)

    op.create_table('Playlist',
    sa.Column('PlaylistId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('PlaylistId')
    )
    with op.batch_alter_table('Playlist', schema=None) as batch_op:
        batch_op.create_index('IPK_Playlist', ['PlaylistId'], unique=1)

    op.create_table('Customer',
    sa.Column('CustomerId', sa.INTEGER(), nullable=False),
    sa.Column('FirstName', sa.NVARCHAR(length=40), nullable=False),
    sa.Column('LastName', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Company', sa.NVARCHAR(length=80), nullable=True),
    sa.Column('Address', sa.NVARCHAR(length=70), nullable=True),
    sa.Column('City', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('State', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('Country', sa.NVARCHAR(length=40), nullable=True),
    sa.Column('PostalCode', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('Phone', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Fax', sa.NVARCHAR(length=24), nullable=True),
    sa.Column('Email', sa.NVARCHAR(length=60), nullable=False),
    sa.Column('SupportRepId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['SupportRepId'], ['Employee.EmployeeId'], ),
    sa.PrimaryKeyConstraint('CustomerId')
    )
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.create_index('IPK_Customer', ['CustomerId'], unique=1)
        batch_op.create_index('IFK_CustomerSupportRepId', ['SupportRepId'], unique=False)

    op.create_table('Track',
    sa.Column('TrackId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('AlbumId', sa.INTEGER(), nullable=True),
    sa.Column('MediaTypeId', sa.INTEGER(), nullable=False),
    sa.Column('GenreId', sa.INTEGER(), nullable=True),
    sa.Column('Composer', sa.NVARCHAR(length=220), nullable=True),
    sa.Column('Milliseconds', sa.INTEGER(), nullable=False),
    sa.Column('Bytes', sa.INTEGER(), nullable=True),
    sa.Column('UnitPrice', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['AlbumId'], ['Album.AlbumId'], ),
    sa.ForeignKeyConstraint(['GenreId'], ['Genre.GenreId'], ),
    sa.ForeignKeyConstraint(['MediaTypeId'], ['MediaType.MediaTypeId'], ),
    sa.PrimaryKeyConstraint('TrackId')
    )
    with op.batch_alter_table('Track', schema=None) as batch_op:
        batch_op.create_index('IPK_Track', ['TrackId'], unique=1)
        batch_op.create_index('IFK_TrackMediaTypeId', ['MediaTypeId'], unique=False)
        batch_op.create_index('IFK_TrackGenreId', ['GenreId'], unique=False)
        batch_op.create_index('IFK_TrackAlbumId', ['AlbumId'], unique=False)

    op.create_table('foo',
    sa.Column('bar', sa.INTEGER(), nullable=True),
    sa.Column('baz', sa.VARCHAR(length=20), nullable=True)
    )
    op.create_table('Artist',
    sa.Column('ArtistId', sa.INTEGER(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('ArtistId')
    )
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.create_index('IPK_Artist', ['ArtistId'], unique=1)

    # ### end Alembic commands ###
